# Generated by Django 3.1.4 on 2020-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pdsid', models.IntegerField()),
                ('basics', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('date_of_joining', models.DateField()),
                ('mobile_no', models.CharField(max_length=11)),
                ('home_district', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
