# Generated by Django 3.1.4 on 2020-12-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
