# Generated by Django 3.1.4 on 2020-12-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20201224_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(verbose_name='বিস্তারিত'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, verbose_name='শিরোনাম'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='basics',
            field=models.CharField(max_length=200, verbose_name='মূলপদ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_joining',
            field=models.DateField(verbose_name='বর্তমান কর্মস্থলে যোগদানের তারিখ'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='home_district',
            field=models.CharField(max_length=200, verbose_name='নিজ জেলা'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(upload_to='uploads/', verbose_name='ছবি'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(max_length=11, verbose_name='মোবাইল নং'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='নাম'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pdsid',
            field=models.IntegerField(verbose_name='পিডিএস আইডি'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=200, verbose_name='পদবী'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.photo')),
            ],
        ),
    ]
