# Generated by Django 3.1.4 on 2020-12-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20201225_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image_file',
        ),
        migrations.AddField(
            model_name='gallery',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='gallry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
