# Generated by Django 3.1.4 on 2020-12-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20201225_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='নাম')),
                ('title', models.CharField(max_length=200, verbose_name='পদবী')),
                ('date_of_joining', models.DateField(verbose_name='বর্তমান কর্মস্থলে যোগদানের তারিখ')),
                ('mobile_no', models.CharField(max_length=11, verbose_name='মোবাইল নং')),
                ('home_district', models.CharField(max_length=200, verbose_name='নিজ জেলা')),
                ('image', models.FileField(upload_to='uploads/', verbose_name='ছবি')),
            ],
        ),
    ]
