# Generated by Django 3.1.4 on 2020-12-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_class_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrincipalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('image', models.FileField(upload_to='uploads/', verbose_name='ছবি')),
            ],
        ),
    ]
